# Generated by Django 4.2 on 2024-07-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_name_type'),
        ),
    ]
