from .path import STORAGE_DIR, env

STORAGE_TYPE = env("STORAGE_TYPE")
STORAGE_AVAILABLE = {
    "local": {
        "ACCESS_KEY": "",
        "ACCESS_SECRET": "",
        "REGION": "",
        "BUCKET": STORAGE_DIR + "local",
    },
    "s3": {
        "ACCESS_KEY": env("STORAGE_ACCESS_KEY"),
        "ACCESS_SECRET": env("STORAGE_ACCESS_SECRET"),
        "REGION": env("STORAGE_REGION"),
        "BUCKET": env("STORAGE_BUCKET"),
    },
}

STORAGE = STORAGE_AVAILABLE[STORAGE_TYPE]

CLOUD_FRONT_BASE_URL = env("CLOUD_FRONT_BASE_URL")
CLOUD_FRONT_KEY_ID = env("CLOUD_FRONT_KEY_ID")
CLOUD_FRONT_RSA_SIGNER = env("CLOUD_FRONT_RSA_SIGNER")
CLOUD_FRONT_LINK_EXPIRED_IN_SECOND = env("CLOUD_FRONT_LINK_EXPIRED_IN_SECOND")

FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
