services:
  nginx:
    image: nginx:latest
    ports:
      - 80:8000
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    depends_on:
      - app

  app:
    image: django_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/data
    ports:
      - ${APP_PORT}
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped
    depends_on:
      - db
      - redis
    command: sh -c "uwsgi --ini ../nginx/uwsgi.ini"

  worker:
    image: django_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/data
    deploy:
      mode: replicated
      replicas: 2
    restart: unless-stopped
    depends_on:
      - db
      - redis
    command: sh -c "python manage.py qcluster"

  db:
    image: mariadb:10.4
    volumes:
      - volume-db:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  redis:
    image: "redis:5.0.6"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass "${REDIS_PASSWORD}"

volumes:
  volume-db:
