services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:8000
    volumes:
      - ./nginx/nginx.deploy.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  redis:
    image: "redis:5.0.6"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass "${REDIS_PASSWORD}"
