services:
  nginx:
    image: nginx:latest
    ports:
      - 80:8000
    volumes:
      - ./deploy/nginx/nginx.local.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    depends_on:
      - app

  app:
    image: luna_manga_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .env:/root/main/.env
      - ./deploy/uwsgi.local.ini:/root/main/uwsgi.ini
      - ./app:/root/main/app
    ports:
      - 8000
    restart: unless-stopped
    depends_on:
      - redis
    command: sh -c "uwsgi --ini /root/main/uwsgi.ini"

  worker:
    image: luna_manga_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .env:/root/main/.env
      - ./app:/root/main/app
    deploy:
      mode: replicated
      replicas: ${APP_WORKER_REPLICAS}
    restart: unless-stopped
    depends_on:
      - redis
    command: sh -c "python manage.py qcluster"

  redis:
    image: "redis:5.0.6"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass "${REDIS_PASSWORD}"
