services:
  db:
    container_name: db
    image: mariadb:10.4
    volumes:
      - volume-db:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  volume-db:
