services:
  worker:
    image: django_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/data
    ports:
      - ${APP_WORKER_PORT} # If VPS run only worker, Port can be 8000 by default.
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped
    command: sh -c "python manage.py qcluster"
