services:
  nginx:
    image: nginx:latest
    ports:
      - 80:8000
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - /tmp:/tmp
    restart: unless-stopped
    depends_on:
      - app

  app:
    image: teeratachdocker/luna_manga_api:latest
    platform: linux/amd64
    volumes:
      - .env:/root/main/.env
      - ./uwsgi.prod.ini:/root/main/uwsgi.ini
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /tmp:/tmp
    ports:
      - 8000
    restart: unless-stopped
    depends_on:
      - redis
    command: sh -c "uwsgi --ini /root/main/uwsgi.ini"

  worker:
    image: teeratachdocker/luna_manga_api:latest
    platform: linux/amd64
    volumes:
      - .env.worker:/root/main/.env
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy:
      mode: replicated
      replicas: ${APP_WORKER_REPLICAS}
    restart: unless-stopped
    depends_on:
      - redis
    command: sh -c "python manage.py qcluster"

  redis:
    image: "redis:5.0.6"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass "${REDIS_PASSWORD}"
# docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}"
