services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    depends_on:
      - app

  app:
    image: teeratachdocker/luna_manga_api:latest
    volumes:
      - .env:/root/main/.env
      - ./uwsgi.ini:/root/main/uwsgi.ini
    ports:
      - 8000
    deploy:
      mode: replicated
      replicas: 1
    restart: unless-stopped
    depends_on:
      - redis
    command: sh -c "uwsgi --ini /root/main/uwsgi.ini"

  worker:
    image: teeratachdocker/luna_manga_api:latest
    volumes:
      - .env.worker:/root/main/.env
    deploy:
      mode: replicated
      replicas: ${APP_WORKER_REPLICAS}
    restart: unless-stopped
    depends_on:
      - redis
    command: sh -c "python manage.py qcluster"

  redis:
    image: "redis:5.0.6"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass "${REDIS_PASSWORD}"

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
