services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - /tmp:/tmp
    restart: unless-stopped
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G

  app:
    image: teeratachdocker/luna_manga_api:latest
    volumes:
      - .env:/root/main/.env
      - ./uwsgi.ini:/root/main/uwsgi.ini
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /tmp:/tmp
    restart: unless-stopped
    command: sh -c "uwsgi --ini /root/main/uwsgi.ini"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 4G

  worker:
    image: teeratachdocker/luna_manga_api:latest
    volumes:
      - .env.worker:/root/main/.env
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    depends_on:
      - redis
    command: sh -c "python manage.py qcluster"
    deploy:
      mode: replicated
      replicas: ${APP_WORKER_REPLICAS}
      resources:
        limits:
          cpus: "1.0"
          memory: 4G

  redis:
    image: "redis:5.0.6"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
# docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}"
