permission = {
    "story.manage": False,
    "story.view": False,
    "chapter.manage": False,
    "chapter.view": False,
    "category.manage": False,
    "category.view": False,
    "customer.manage": False,
    "customer.view": False,
    "customer_group.manage": False,
    "customer_group.view": False,
    "user.manage": False,
    "user.view": False,
    "roles_and_permission.manage": False,
    "roles_and_permission.view": False,
    "banner.manage": False,
    "banner.view": False,
    "widget.manage": False,
    "widget.view": False,
    "customer_report.manage": False,
    "customer_report.view": False,
    "file.view": False,
    "file.manage": False,
    "oauth_client.manage": False,
    "oauth_client.view": False,
}
