# Generated by Django 4.2 on 2024-07-14 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150)),
                ('title', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('link', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=300)),
                ('status', models.CharField(default='inactive', max_length=30)),
                ('model_id', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banners',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150, unique=True)),
                ('type', models.CharField(max_length=150)),
                ('status', models.CharField(default='inactive', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150)),
                ('chapter_number', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(db_collation='utf8mb4_unicode_ci')),
                ('type', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'chapters',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(db_collation='utf8mb4_unicode_ci')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chapter')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configurations',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('nick_name', models.CharField(db_collation='utf8mb4_unicode_ci', default=None, max_length=150, null=True)),
                ('first_name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150)),
                ('last_name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150)),
                ('phone_number', models.CharField(default=None, max_length=20, null=True)),
                ('status', models.CharField(default='inactive', max_length=30)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('email_verified_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150, unique=True)),
                ('status', models.CharField(default='inactive', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_groups',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('file_name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255)),
                ('mime_type', models.CharField(db_index=True, max_length=255)),
                ('collection_name', models.CharField(db_index=True, max_length=255)),
                ('conversion', models.TextField(default=None, null=True)),
                ('size_bytes', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('client_secret', models.CharField(max_length=255, unique=True)),
                ('redirect_url', models.CharField(default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oauth_clients',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('guard_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(db_collation='utf8mb4_unicode_ci')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=200, unique=True)),
                ('name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150, unique=True)),
                ('author_name', models.CharField(db_collation='utf8mb4_unicode_ci', default=None, max_length=150, null=True)),
                ('description', models.TextField(db_collation='utf8mb4_unicode_ci')),
                ('type', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='app.category')),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.customer')),
            ],
            options={
                'db_table': 'stories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('nick_name', models.CharField(db_collation='utf8mb4_unicode_ci', default=None, max_length=30, null=True)),
                ('first_name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150)),
                ('last_name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150)),
                ('phone_number', models.CharField(default=None, max_length=20, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('status', models.CharField(default='inactive', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150)),
                ('title', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('status', models.CharField(default='inactive', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.user')),
            ],
            options={
                'db_table': 'widgets',
            },
        ),
        migrations.CreateModel(
            name='WidgetSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.widget')),
            ],
            options={
                'db_table': 'widgets_sequence',
            },
        ),
        migrations.CreateModel(
            name='WidgetBanner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.banner')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.widget')),
            ],
            options={
                'db_table': 'widgets_banners',
            },
        ),
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.story')),
            ],
            options={
                'db_table': 'stories_reaction',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guard_name', models.CharField(max_length=255)),
                ('name', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=150, unique=True)),
                ('description', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_permissions', models.ManyToManyField(to='app.permission')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
            options={
                'db_table': 'posts_reactions',
            },
        ),
        migrations.CreateModel(
            name='OAuthAccessToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('model_id', models.PositiveIntegerField(default=None, null=True)),
                ('access_token', models.TextField(max_length=500, unique=True)),
                ('refresh_token', models.TextField(max_length=500, unique=True)),
                ('scopes', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expired_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(default=None, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.oauthclient')),
                ('model_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'oauth_access_tokens',
            },
        ),
        migrations.CreateModel(
            name='ModelHasRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.PositiveIntegerField()),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
            options={
                'db_table': 'model_has_roles',
            },
        ),
        migrations.CreateModel(
            name='Fileable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.PositiveIntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.file')),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'fileables',
            },
        ),
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=150)),
                ('is_accept', models.BooleanField(default=False)),
                ('model_id', models.PositiveIntegerField()),
                ('message', models.CharField(db_collation='utf8mb4_unicode_ci', default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accept_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.user')),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.customer')),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'customer_reports',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.customergroup'),
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
            options={
                'db_table': 'comments_reactions',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.CreateModel(
            name='ChapterReaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chapter')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
            options={
                'db_table': 'chapters_reactions',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.story'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.story')),
            ],
            options={
                'db_table': 'bookmarks',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.user'),
        ),
        migrations.AddConstraint(
            model_name='modelhasrole',
            constraint=models.UniqueConstraint(fields=('role', 'model_type', 'model_id'), name='unique_model_has_role'),
        ),
    ]
