# Generated by Django 4.2 on 2024-08-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_oauthaccesstoken_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='text',
            field=models.TextField(db_collation='utf8mb4_unicode_ci', default=None, null=True),
        ),
    ]
