# Generated by Django 4.2 on 2024-09-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_chapter_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_index=True, max_length=200, unique=True),
        ),
    ]
