# Generated by Django 4.2 on 2024-09-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_story_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=300),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=300),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.CharField(db_collation='utf8mb4_unicode_ci', db_index=True, max_length=300, unique=True),
        ),
    ]
