# Generated by Django 4.2 on 2025-02-16 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_banner_name_alter_banner_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTracking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_url', models.CharField(db_collation='utf8mb4_unicode_ci', default=None, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.customer')),
            ],
            options={
                'db_table': 'customer_tracking',
            },
        ),
    ]
