# Generated by Django 4.2 on 2025-02-16 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertracking',
            name='token',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.oauthaccesstoken'),
        ),
    ]
